spring:
  application:
    name: backend

  cloud:
    aws:
      s3:
        bucket: insurtech-claim-file-bucket
      region:
        static: eu-central-1
      credentials: # Specify only for local running to get access to AWS
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}